Repository team-winey/Winey-AOS, pull requests merged in 2023-11, with the labels that each got.

#220 [fix] 릴리즈 모드에 Proguard 적용 시, 카카오 로그인 안 되는 이슈 해결
  .github/workflows/pr_checker.yml
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/org/go/sopt/winey/data/source/KakaoLoginDataSource.kt
  app/src/main/java/org/go/sopt/winey/di/ServiceModule.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
Labels: fix 💥, 하은 🐰

#222 [fix] 상세 피드 / 댓글 입력창 바깥을 터치했을 때만 키보드가 내려가도록
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
Labels: fix 💥, 하은 🐰

#223 [merge] v.1.0.1 버전 태그 생성
  .github/workflows/pr_checker.yml
  .gitignore
  README.md
  app/build.gradle.kts
  app/proguard-rules.pro
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/data/source/KakaoLoginDataSource.kt
  app/src/main/java/org/go/sopt/winey/di/ServiceModule.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedHeaderAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingDialogFragment.kt
  app/src/main/res/drawable/img_insta.png
  app/src/main/res/layout/layout_wineyfeed_banner_instagram.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: 하은 🐰, merge 🔀

#225 [refactor] 위니 다이얼로그 프래그먼트 / 생성자 사용하지 않고 번들 사용하기
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/PhotoFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/WineyDialogLabel.kt
  app/src/main/java/org/go/sopt/winey/util/fragment/WineyDialogFragment.kt
  app/src/main/java/org/go/sopt/winey/util/intent/ArgsExt.kt
  app/src/main/java/org/go/sopt/winey/util/intent/IntentExt.kt
  app/src/main/res/layout/fragment_alert_dialog.xml
Labels: 상욱 🐨, refactor 🧹

#228 [feat] 위니피드, 상세피드 / 신고하기 구글폼 연결
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/nickname/NicknameActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/org/go/sopt/winey/util/activity/ActivityExt.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/fragment/WineyDialogFragment.kt
Labels: feat ✨, 하은 🐰
