Repository team-winey/Winey-AOS, pull requests merged in 2023-10, with the labels that each got.

#200 [hotfix] 기초세팅 / 다크모드 비활성화
  README.md
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/WineyApplication.kt
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseDeleteFeedDto.kt
  app/src/main/java/org/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/org/go/sopt/winey/data/service/FeedService.kt
  app/src/main/java/org/go/sopt/winey/data/source/FeedDataSource.kt
  app/src/main/java/org/go/sopt/winey/data/source/paging/BasePagingSource.kt
  app/src/main/java/org/go/sopt/winey/data/source/paging/MyFeedPagingSource.kt
  app/src/main/java/org/go/sopt/winey/data/source/paging/WineyFeedPagingSource.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/WineyFeed.kt
  app/src/main/java/org/go/sopt/winey/domain/repository/FeedRepository.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedLoadAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageNotOverDialogFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/nickname/NicknameActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/nickname/NicknameViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/code/ErrorCode.kt
  app/src/main/java/org/go/sopt/winey/util/multipart/UriToRequestBody.kt
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/fragment_mypage_not_over_dialog.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/DefaultConfig.kt
  buildSrc/src/main/java/Plugins.kt
Labels: hotfix 🚨, 하은 🐰

#201 [hotfix] 기초세팅 / 다크모드 비활성화
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/WineyApplication.kt
  buildSrc/src/main/java/DefaultConfig.kt
Labels: hotfix 🚨, 하은 🐰

#203 [hotfix] 스플래시 / 안드로이드 12 미만 버전 대응
  app/release/output-metadata.json
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: hotfix 🚨, 하은 🐰

#204 [merge] 스플래시 / 안드로이드 버전 12 미만 대응
  app/release/output-metadata.json
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: 하은 🐰, merge 🔀

#210 [feat,ui] 위니피드 / 인스타 배너 추가 및 링크 연결 구현
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedHeaderAdapter.kt
  app/src/main/res/drawable/img_insta.png
  app/src/main/res/layout/layout_wineyfeed_banner_instagram.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 혜선 🐱

#211 [add] 기초 세팅 / R8컴파일러로 앱 경량화, 난독화
  app/build.gradle.kts
Labels: add ➕, 혜선 🐱

#209 [comment] 마이페이지 / 목표설정 관련 주석 수정
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
Labels: 하은 🐰, comment 💬

#213 [feat] 위니 피드 / 기간 내 목표 달성 시 축하 다이얼로그 띄우기
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingDialogFragment.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: feat ✨, 하은 🐰

#215 [fix] 기초 세팅 / 난독화 후 앱 크래시 현상 해결
  app/proguard-rules.pro
  app/release/output-metadata.json
  buildSrc/src/main/java/DefaultConfig.kt
Labels: fix 💥, 혜선 🐱
