Repository team-winey/Winey-AOS, pull requests merged in 2023-08, with the labels that each got.

#96 [refactor] 마이페이지, 추천위니 / 리팩토링
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/request/RequestCreateGoalDto.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
  app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
Labels: 상욱 🐨, refactor 🧹

#98 [refactor] 위니 피드, 마이 피드 / 리팩토링
  app/build.gradle.kts
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteHighDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteLowDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/res/layout/fragment_feed_delete_dialog.xml
  app/src/main/res/layout/fragment_myfeed_highlevel_delete_dialog.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: 혜선 🐱, refactor 🧹

#100 [refactor] 위니 업로드 / 리팩토링 일부
  .github/workflows/pr_checker.yml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/content/ContentViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/photo/PhotoFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/photo/PhotoViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/util/multipart/BitmapRequestBody.kt
  app/src/main/java/com/android/go/sopt/winey/util/multipart/ImageCompressor.kt
  app/src/main/java/com/android/go/sopt/winey/util/multipart/UriToRequestBody.kt
  app/src/main/java/com/android/go/sopt/winey/util/view/UiState.kt
  app/src/main/res/drawable/sel_upload_edittext_focus_color.xml
  app/src/main/res/drawable/shape_red_line_10_rect.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_photo.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 하은 🐰, refactor 🧹

#103 [feat] 온보딩 / 카카오 로그인 구현
  .github/workflows/pr_checker.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/WineyApplication.kt
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/request/RequestLoginDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseLoginDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseReIssueTokenDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/KakaoLoginRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/KakaoLoginService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/KakaoLoginDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/di/DataStoreModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/KakaoModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/RepositoryModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/ServiceModule.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/Login.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/ReIssueToken.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/User.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/DataStoreRepository.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/KakaoLoginRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/KakaoLoginCallback.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/LoginActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/LoginViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_login_kakao.xml
  app/src/main/res/drawable/ic_login_saver.xml
  app/src/main/res/drawable/ic_login_title.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  settings.gradle.kts
Labels: feat ✨, 상욱 🐨

#106 [ui] 마이페이지 뷰, 추천 뷰 / 변경된 디자인에 맞게 리디자인
  app/src/main/res/drawable/ic_recommend_item_saver.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
  app/src/main/res/layout/item_recommend_header.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 상욱 🐨

#107 [feat] 온보딩 / 닉네임 뷰 구현, 중복체크 서버 통신
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetNicknameDuplicateCheckDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/KakaoLoginCallback.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/LoginViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/util/code/NicknameErrorCode.kt
  app/src/main/java/com/android/go/sopt/winey/util/view/InputUiState.kt
  app/src/main/res/drawable/sel_nickname_edittext_focus_color.xml
  app/src/main/res/drawable/sel_upload_nickname_btn_color.xml
  app/src/main/res/drawable/sel_upload_nickname_btn_text_color.xml
  app/src/main/res/drawable/shape_blue_line_5_rect.xml
  app/src/main/res/drawable/shape_gray_line_5_rect.xml
  app/src/main/res/drawable/shape_purple_line_5_rect.xml
  app/src/main/res/drawable/shape_red_line_5_rect.xml
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_photo.xml
  app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#108 [feat] 위니피드, 마이피드 / Paging3 적용 + 로딩 프로그레스바 구현
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetWineyFeedListDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/RecommendRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/FeedService.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/RecommendService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/FeedDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/RecommendDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/paging/BasePagingSource.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/paging/MyFeedPagingSource.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/paging/WineyFeedPagingSource.kt
  app/src/main/java/com/android/go/sopt/winey/di/RepositoryModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/ServiceModule.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/WineyFeed.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/FeedRepository.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/RecommendRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedLoadAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDialogViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/layout/item_feed_loading_footer.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
Labels: feat ✨, 혜선 🐱

#112 [feat] 온보딩 / 로그아웃 서버통신 구현
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseLogoutDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/LoginViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
Labels: feat ✨, 상욱 🐨

#114 [feat] 온보딩 / 가이드, 스토리, 닉네임 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/assets/images/img_0.png
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/request/RequestPatchNicknameDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/GuideActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/GuideFragmentStateAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/LevelGuideFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/RecommendGuideFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/WineyFeedGuideFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/FirstStoryFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/SecondStoryFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/StoryViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/ThirdStoryFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/bg_story_lottie.png
  app/src/main/res/drawable/ic_story_arrow_next.xml
  app/src/main/res/drawable/img_guide_level.png
  app/src/main/res/drawable/img_guide_recommend.png
  app/src/main/res/drawable/img_guide_wineyfeed.png
  app/src/main/res/drawable/img_story_saver.xml
  app/src/main/res/drawable/shape_gray_line_left10_bottom10_rect.xml
  app/src/main/res/drawable/shape_gray_line_top10_rect.xml
  app/src/main/res/drawable/shape_white_fill_gray_line_right10_bottom10_rect.xml
  app/src/main/res/drawable/shape_white_gradient_rect.xml
  app/src/main/res/drawable/shape_yellow_fill_gray_line_right10_bottom10_rect.xml
  app/src/main/res/layout/activity_guide.xml
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/activity_story.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_first_story.xml
  app/src/main/res/layout/fragment_level_guide.xml
  app/src/main/res/layout/fragment_recommend_guide.xml
  app/src/main/res/layout/fragment_second_story.xml
  app/src/main/res/layout/fragment_third_story.xml
  app/src/main/res/layout/fragment_winey_feed_guide.xml
  app/src/main/res/raw/lottie_splash.json
  app/src/main/res/raw/lottie_story_first.json
  app/src/main/res/raw/lottie_story_second.json
  app/src/main/res/raw/lottie_story_third.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: feat ✨, 하은 🐰

#116 [ui] 다이얼로그 / 다이얼로그 디자인 통일
  app/src/main/java/com/android/go/sopt/winey/presentation/main/AlertDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_alert_dialog.xml
  app/src/main/res/layout/fragment_mypage_not_over_dialog.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 상욱 🐨

#121 [ui] 위니 피드, 마이 피드 / 리디자인 뷰 구현
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/res/drawable/ic_wineyfeed_comment.xml
  app/src/main/res/drawable/ic_wineyfeed_notification_new.xml
  app/src/main/res/drawable/ic_wineyfeed_notification_none.xml
  app/src/main/res/drawable/img_comment_empty.xml
  app/src/main/res/drawable/img_myfeed_empty.xml
  app/src/main/res/drawable/img_wineyfeed_banner_1.xml
  app/src/main/res/drawable/img_wineyfeed_banner_2.xml
  app/src/main/res/drawable/img_wineyfeed_banner_3.xml
  app/src/main/res/drawable/img_wineyfeed_banner_4.png
  app/src/main/res/drawable/img_wineyfeed_saver.xml
  app/src/main/res/drawable/img_wineyfeed_seperator.xml
  app/src/main/res/drawable/shape_gray50_fill_10_rect.xml
  app/src/main/res/layout/fragment_myfeed.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_header.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/layout/menu_wineyfeed.xml
  app/src/main/res/menu/menu_wineyfeed.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 혜선 🐱

#118 [feat] 마이페이지, 위니업로드 / 닉네임 수정, 회원탈퇴, 리디자인 적용
  app/src/main/AndroidManifest.xml
  app/src/main/assets/images/img_0.png
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/DataStoreRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/ContentFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/PhotoFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/content/ContentViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/photo/PhotoViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/nickname/NicknameActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/nickname/NicknameViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/com/android/go/sopt/winey/util/context/ContextExt.kt
  app/src/main/java/com/android/go/sopt/winey/util/fragment/FragmentExt.kt
  app/src/main/java/com/android/go/sopt/winey/util/fragment/WineyDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/view/WineySnackbar.kt
  app/src/main/res/drawable/ic_snackbar_fail.xml
  app/src/main/res/drawable/ic_snackbar_success.xml
  app/src/main/res/drawable/ic_upload_nickname_close.xml
  app/src/main/res/drawable/shape_gray100_fill_5_rect.xml
  app/src/main/res/drawable/shape_gray700_fill_5_rect.xml
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_photo.xml
  app/src/main/res/layout/layout_winey_snackbar.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#126 [feat] 위니피드, 마이피드 / 삭제 다이얼로그 통일
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDialogViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/fragment/WineyDialogFragment.kt
  app/src/main/res/layout/fragment_wineyfeed_no_goal_dialog.xml
  app/src/main/res/layout/layout_winey_snackbar.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#131 [fix] 온보딩 / 세계관 스토리 2번째 로티 애니메이션 오류 해결
  app/src/main/res/raw/lottie_story_second.json
Labels: fix 💥, 하은 🐰

#123 [ui] 알림 / 알림 뷰 디자인
  app/src/main/java/com/android/go/sopt/winey/domain/entity/Notification.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/ic_mypage_lv_help.xml
  app/src/main/res/drawable/ic_notification_comment.xml
  app/src/main/res/drawable/ic_notification_like.xml
  app/src/main/res/drawable/ic_notification_logo.xml
  app/src/main/res/drawable/ic_notification_lv1.xml
  app/src/main/res/drawable/ic_notification_lv2.xml
  app/src/main/res/drawable/ic_notification_lv3.xml
  app/src/main/res/drawable/ic_notification_lv4.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_notification_post.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 상욱 🐨

#127 [mod] 세계관 스토리 / 뒤로가기 불가능 하도록 변경
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
Labels: mod 〰, 하은 🐰

#125 [feat] 위니 피드 / 상세페이지 피드, 댓글 조회
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetFeedDetailDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/FeedService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/FeedDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/DetailFeed.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/FeedRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/img_comment_empty.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_feed_delete_dialog.xml
  app/src/main/res/layout/item_detail_comment.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 혜선 🐱

#134 [feat] 마이 피드 / 상세페이지 피드, 댓글 조회
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/res/layout/item_myfeed_post.xml
Labels: feat ✨, 혜선 🐱

#138 [feat] 상세 피드 / 피드와 댓글 같이 스크롤 되도록 구현
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/request/RequestPostCommentDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetFeedDetailDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponsePostCommentDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/FeedService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/FeedDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/DetailFeed.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/FeedRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentEmptyAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/shape_white_fill_10_rect.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_detail_comment.xml
  app/src/main/res/layout/item_detail_comment_empty.xml
  app/src/main/res/layout/item_detail_feed.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#137 [feat] 알림 / 알림 받아오기 서버연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetNotificationDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseHasNewNotificationDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/NotificationRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/NotificationService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/NotificationDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/di/RepositoryModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/ServiceModule.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/Notification.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/NotificationRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/layout/item_notification_post.xml
Labels: feat ✨, 상욱 🐨

#139 [feat] 상세 피드 / 댓글 생성
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponsePostCommentDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/FeedService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/FeedDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/DetailFeed.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/FeedRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/view/WineyPopupMenu.kt
  app/src/main/res/drawable/shape_transparent_fill_5_rect.xml
  app/src/main/res/drawable/shape_white_fill_5_rect.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_winey_popup.xml
  app/src/main/res/layout/layout_winey_popup.xml
  app/src/main/res/layout/menu_wineyfeed.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#140 [feat] 상세 피드 / 피드 좋아요, 삭제, 신고 구현
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/res/values/strings.xml
Labels: feat ✨, 혜선 🐱

#144 [feat] 상세 피드 / 댓글 삭제 및 신고 기능 구현
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseDeleteCommentDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseDeleteWineyFeedDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/FeedService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/FeedDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/FeedRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
  app/src/main/res/layout/item_detail_feed.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
Labels: feat ✨, 하은 🐰

#142 [fix] 알림 / 알림 기능 오류 수정
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationAdapter.kt
Labels: fix 💥, 상욱 🐨

#146 [fix] 상세 피드 / 댓글 생성, 삭제 후 empty 뷰 전환하기
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentEmptyAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/layout_comment_empty.xml
Labels: fix 💥, 하은 🐰

#148 [feat] 위니피드, 마이피드 / 리디자인 및 리팩토링
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedHeaderAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_header.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
Labels: feat ✨, 혜선 🐱

#149 [fix] 위니 업로드 / 절약 내용 에디트텍스트가 비어있으면 버튼 활성화 되지 않도록 변경
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/nickname/NicknameViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/util/code/ErrorCode.kt
  app/src/main/java/com/android/go/sopt/winey/util/view/InputUiState.kt
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/fragment_content.xml
Labels: fix 💥, 하은 🐰

#155 [mod] 온보딩 / 1차 릴리즈 QA 피드백 반영
  app/src/main/java/com/android/go/sopt/winey/presentation/nickname/NicknameActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/nickname/NicknameViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/GuideActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/FirstStoryFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/SecondStoryFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/ThirdStoryFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/sel_nickname_edittext_focus_color.xml
  app/src/main/res/drawable/sel_upload_nickname_btn_color.xml
  app/src/main/res/drawable/shape_gray200_fill_10_rect.xml
  app/src/main/res/drawable/shape_gray200_line_5_rect.xml
  app/src/main/res/drawable/shape_gray900_line_5_rect.xml
  app/src/main/res/drawable/shape_gray900_line_cursor.xml
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/activity_story.xml
  app/src/main/res/layout/fragment_first_story.xml
  app/src/main/res/layout/fragment_second_story.xml
  app/src/main/res/layout/fragment_third_story.xml
  app/src/main/res/values/strings.xml
Labels: mod 〰, ui 🎨, 하은 🐰

#158 [mod] 상세 피드 댓글 / 1차 릴리즈 QA 피드백 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/sel_upload_edittext_focus_color.xml
  app/src/main/res/drawable/shape_gray100_line_10_rect.xml
  app/src/main/res/drawable/shape_gray_line_10_rect.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_myfeed.xml
  app/src/main/res/layout/fragment_photo.xml
  app/src/main/res/layout/item_detail_feed.xml
Labels: mod 〰, ui 🎨, 하은 🐰

#161 [fix] 메인, 마이페이지 / QA 반영 및 탈퇴한 유저 처리
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: fix 💥, 상욱 🐨

#162 [mod] 위니 업로드 / 사진 업로드 프래그먼트에서만 경고 다이얼로그가 뜨도록 변경
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/PhotoFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
Labels: mod 〰, 하은 🐰

#159 [fix] 위니피드, 마이피드 / 스크롤 위치 문제, 좋아요 ui 반영문제 해결
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
Labels: fix 💥, 혜선 🐱

#163 [mod] 위니피드, 마이피드, 상세페이지 / 1차 릴리즈 qa 피드백 반영
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/res/drawable/img_wineyfeed_banner_4.png
  app/src/main/res/drawable/img_wineyfeed_banner_4.xml
  app/src/main/res/layout/fragment_myfeed.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/layout/item_detail_feed.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_header.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
Labels: mod 〰, 혜선 🐱

#165 [feat] 알림 / 스와이프 새로고침 기능추가
  app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
  app/src/main/res/layout/activity_notification.xml
Labels: feat ✨, 상욱 🐨

#167 [mod] 마이피드 / 1차 릴리즈 QA 피드백 반영
  app/src/main/res/drawable/img_myfeed_empty.xml
  app/src/main/res/layout/fragment_myfeed.xml
Labels: 혜선 🐱

#166 [chore] 데이터 태깅 / 앰플리튜드 설정하기
  .github/workflows/pr_checker.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/di/AmplitudeModule.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/ContentFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/PhotoFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/nickname/NicknameActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/GuideActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/guide/GuideFragmentStateAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/java/com/android/go/sopt/winey/util/amplitude/AmplitudeUtils.kt
  app/src/main/java/com/android/go/sopt/winey/util/amplitude/type/EventType.kt
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: chore 🛠, 하은 🐰

#168 [mod] 위니 피드 / 랜덤 배너 디자인 수정
  app/release/output-metadata.json
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedHeaderAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/img_wineyfeed_banner1.xml
  app/src/main/res/drawable/img_wineyfeed_banner2.xml
  app/src/main/res/drawable/img_wineyfeed_banner3.xml
  app/src/main/res/drawable/img_wineyfeed_banner4.xml
  app/src/main/res/drawable/img_wineyfeed_banner_1.xml
  app/src/main/res/drawable/img_wineyfeed_banner_2.xml
  app/src/main/res/drawable/img_wineyfeed_banner_3.xml
  app/src/main/res/drawable/img_wineyfeed_banner_4.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_wineyfeed_header.xml
  app/src/main/res/layout/layout_wineyfeed_banner1.xml
  app/src/main/res/layout/layout_wineyfeed_banner2.xml
  app/src/main/res/layout/layout_wineyfeed_banner3.xml
  app/src/main/res/layout/layout_wineyfeed_banner4.xml
  app/src/main/res/values/strings.xml
Labels: mod 〰, ui 🎨, 하은 🐰

#175 [mod] 위니 업로드 / 0~499원 로딩 뷰 수정
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/com/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/layout_wineyfeed_banner1.xml
  app/src/main/res/layout/layout_wineyfeed_banner2.xml
  app/src/main/res/layout/layout_wineyfeed_banner3.xml
  app/src/main/res/layout/layout_wineyfeed_banner4.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/save_item_categories.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: mod 〰, fix 💥, ui 🎨, 하은 🐰

#177 [mod] 마이페이지 / 기간 내 목표를 달성한 순간에는 유저 데이터 유지
  app/release/output-metadata.json
  app/src/main/java/com/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/go/sopt/winey/presentation/main/mypage/MyPageNotOverDialogFragment.kt
  buildSrc/src/main/java/DefaultConfig.kt
Labels: mod 〰, 하은 🐰
