Repository team-winey/Winey-AOS, pull requests merged in 2023-07, with the labels that each got.

#2 [ui] 기초 세팅 / 컬러, 폰트 적용
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extrabold.otf
  app/src/main/res/font/pretendard_extralight.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/font/pretendard_thin.otf
  app/src/main/res/font/winey_pretendard_bold.xml
  app/src/main/res/font/winey_pretendard_medium.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ui 🎨, 상욱 🐨

#3 [chore] 기초세팅 / 패키징, hilt 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/Application.kt
  app/src/main/java/com/android/go/sopt/winey/di/RepositoryModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/RetrofitModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/ServiceModule.kt
  app/src/main/java/com/android/go/sopt/winey/domain/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recommend.xml
Labels: add ➕, 혜선 🐱

#5 [mod] 기초세팅 / 바인딩 액티비티, 프래그먼트 적용
  app/build.gradle.kts
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/values/themes.xml
Labels: mod 〰

#6 [feat] main / 바텀네비게이션 바 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/WineyApplication.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/res/drawable/ic_main_feed.xml
  app/src/main/res/drawable/ic_main_mypage.xml
  app/src/main/res/drawable/ic_main_recommend.xml
  app/src/main/res/drawable/sel_main_bnv_icon_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat ✨, 상욱 🐨

#9 [chore] 기초 세팅 / 매니페스트 파일
  app/src/main/AndroidManifest.xml
Labels: chore 🛠, 하은 🐰

#11 [mod] 바텀 네비게이션 / MaterialComponents 사용하도록 변경
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/themes.xml
Labels: mod 〰, 하은 🐰

#19 [ui] 위니 피드 / 뷰 구현
  app/build.gradle.kts
  app/src/main/java/com/android/go/sopt/winey/domain/model/WineyFeedModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedHeaderAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingDialogFragment.kt
  app/src/main/res/drawable/ic_wineyfeed_caution.xml
  app/src/main/res/drawable/ic_wineyfeed_disliked.xml
  app/src/main/res/drawable/ic_wineyfeed_liked.xml
  app/src/main/res/drawable/ic_wineyfeed_more.xml
  app/src/main/res/drawable/ic_wineyfeed_upload.xml
  app/src/main/res/drawable/img_wineyfeed_app_bar.xml
  app/src/main/res/drawable/img_wineyfeed_default.png
  app/src/main/res/drawable/img_wineyfeed_profile.png
  app/src/main/res/drawable/shape_gray_fill_12_rect.xml
  app/src/main/res/drawable/shape_gray_fill_5_rect.xml
  app/src/main/res/drawable/shape_yellow_fill_5_rect.xml
  app/src/main/res/drawable/shape_yellow_fill_99_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_wineyfeed_alert_no_goal.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/layout/item_wineyfeed_header.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: ui 🎨, 혜선 🐱

#20 [ui] 위니 업로드 / 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/ContentFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/PhotoFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
  app/src/main/java/com/android/go/sopt/winey/util/activity/ActivityExt.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingActivity.kt
  app/src/main/java/com/android/go/sopt/winey/util/context/ContextExt.kt
  app/src/main/res/drawable/ic_upload_back.xml
  app/src/main/res/drawable/ic_upload_close.xml
  app/src/main/res/drawable/ic_upload_gallery.xml
  app/src/main/res/drawable/sel_upload_content_edittext_stroke_color.xml
  app/src/main/res/drawable/sel_upload_next_btn_bg_color.xml
  app/src/main/res/drawable/sel_upload_next_btn_text_color.xml
  app/src/main/res/drawable/shape_gray_fill_10_rect.xml
  app/src/main/res/drawable/shape_gray_fill_circle.xml
  app/src/main/res/drawable/shape_gray_line_10_rect.xml
  app/src/main/res/drawable/shape_purple_fill_10_rect.xml
  app/src/main/res/drawable/shape_purple_fill_circle.xml
  app/src/main/res/drawable/shape_purple_line_10_rect.xml
  app/src/main/res/drawable/shape_purple_line_cursor.xml
  app/src/main/res/drawable/shape_yellow_fill_10_rect.xml
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_photo.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ui 🎨, 하은 🐰

#23 [fix] 스타일 네이밍 변경, 오탈자 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/themes.xml
Labels: fix 💥, 상욱 🐨

#32 [chore] 서버연결 / AuthInterceptor 추가
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/di/RetrofitModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/qualifier/InterceptorQualifier.kt
Labels: chore 🛠, 상욱 🐨

#35 [feat] 마이페이지 / 유저정보 받아오기 서버연결
  app/build.gradle.kts
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/di/RepositoryModule.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/User.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/layout/activity_mypage_help.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/src/main/java/Plugins.kt
Labels: feat ✨, 상욱 🐨

#37 [feat] 위니 피드 / 피드 불러오기 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetWineyFeed.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/di/RepositoryModule.kt
  app/src/main/java/com/android/go/sopt/winey/di/RetrofitModule.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/WineyFeed.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/WineyFeedModel.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  build.gradle.kts
Labels: feat ✨, 혜선 🐱

#40 [feat] 마이페이지 / 뷰 기능 구현
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/User.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/res/drawable/ic_help_rule.xml
  app/src/main/res/drawable/ic_help_saver_back.xml
  app/src/main/res/drawable/ic_help_saver_front.xml
  app/src/main/res/layout/activity_mypage_help.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 상욱 🐨

#48 [feat] 목표설정 바텀시트 / 목표설정 바텀시트 뷰 기능 구현
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
  app/src/main/res/drawable/sel_target_amount_til_stroke_color.xml
  app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat ✨, 상욱 🐨

#47 [feat] 마이 피드 / 피드 불러오기 구현
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
  app/src/main/res/layout/item_myfeed_post.xml
Labels: feat ✨, 혜선 🐱

#50 [feat] 위니 업로드 / 서버에 피드 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetWineyFeedListDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponsePostWineyFeedDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/base/BaseResponse.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/content/ContentFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/photo/PhotoFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/context/UriToRequestBody.kt
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/layout/fragment_my_page.xml
  build.gradle.kts
Labels: feat ✨, 하은 🐰

#51 [add] 누락된 파일 추가
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetWineyFeedDto.kt
Labels: add ➕, 하은 🐰

#52 [feat] 목표설정 바텀시트/ 목표설정하기 서버연결
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/request/RequestCreateGoalDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseCreateGoalDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/Goal.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat ✨, 상욱 🐨

#54 [ui] 마이페이지 뷰 / 뷰 디자인 수정, 프로필 이미지 추가
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_mypage_edit_btn.xml
  app/src/main/res/drawable/ic_mypage_lv1_profile.xml
  app/src/main/res/drawable/ic_mypage_lv2_profile.xml
  app/src/main/res/drawable/ic_mypage_lv3_profile.xml
  app/src/main/res/drawable/ic_mypage_lv4_profile.xml
  app/src/main/res/drawable/ic_mypage_lv_help.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: ui 🎨, 상욱 🐨

#56 [fix] 위니 업로드 / 이미지 크기 및 회전 각도 조정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/BitmapRequestBody.kt
  app/src/main/java/com/android/go/sopt/winey/util/ImageCompressor.kt
  app/src/main/java/com/android/go/sopt/winey/util/context/UriToRequestBody.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: fix 💥, 하은 🐰

#57 [ui] 추천 위니 / 추천위니 뷰 디자인
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/Recommend.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendHeaderAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
  app/src/main/res/drawable/ic_recommend_item_dummy.xml
  app/src/main/res/drawable/ic_recommend_item_link.xml
  app/src/main/res/drawable/ic_recommend_item_saver.xml
  app/src/main/res/drawable/ic_recommend_logo.xml
  app/src/main/res/drawable/sel_recommend_link_btn_bg_color.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/item_recommend_header.xml
  app/src/main/res/layout/item_recommend_post.xml
Labels: ui 🎨, 상욱 🐨

#60 [feat] 추천 위니 / 추천 피드 받아오기 서버연결
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetRecommendListDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
  app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/User.kt
  app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
  app/src/main/res/layout/item_recommend_post.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 상욱 🐨

#61 [feat] 위니 업로드 / 로딩 화면 구현
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/photo/PhotoFragment.kt
  app/src/main/res/drawable/img_loading_down_arrow.xml
  app/src/main/res/drawable/img_loading_title_highlight.xml
  app/src/main/res/drawable/img_upload_photo.xml
  app/src/main/res/drawable/shape_yellow_fill_rect.xml
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/raw/upload_loading_anim.json
  app/src/main/res/values/save_amount_range.xml
  app/src/main/res/values/save_item_categories.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#62 [del] 기초 세팅 / leakCanary 디펜던시 삭제
  app/build.gradle.kts
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
Labels: chore 🛠, 하은 🐰

#63 [feat] 위니 피드 / 후작업 반영
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/img_feed_default.xml
  app/src/main/res/drawable/img_wineyfeed_app_bar.xml
  app/src/main/res/drawable/img_wineyfeed_default.png
  app/src/main/res/drawable/img_wineyfeed_profile_1.xml
  app/src/main/res/drawable/img_wineyfeed_profile_2.xml
  app/src/main/res/drawable/img_wineyfeed_profile_3.xml
  app/src/main/res/drawable/img_wineyfeed_profile_4.xml
  app/src/main/res/drawable/img_wineyfeed_saver.xml
  app/src/main/res/drawable/shape_gray100_fill_5_fect.xml
  app/src/main/res/layout/fragment_myfeed_highlevel_delete_dialog.xml
  app/src/main/res/layout/fragment_myfeed_lowlevel_delete_dialog.xml
  app/src/main/res/layout/item_wineyfeed_header.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/menu/menu_wineyfeed.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 혜선 🐱

#66 [feat] 마이 피드 / 좋아요, 취소 구현
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
  app/src/main/res/drawable/img_myfeed_empty.xml
  app/src/main/res/layout/fragment_myfeed.xml
  app/src/main/res/layout/myfeed_empty.xml
Labels: feat ✨, 혜선 🐱

#67 [feat] 위니 피드 / 피드 삭제하기 구현
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
Labels: feat ✨, 혜선 🐱

#70 [fix] 마이페이지뷰, 목표설정 바텀시트 / 자잘한 오류 해결, 코드 리팩토링
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MypageHelpActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
  app/src/main/res/values/strings.xml
Labels: fix 💥, 상욱 🐨

#72 [fix] 위니 업로드 / 자잘한 버그 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetRecommendListDto.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/content/ContentFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/content/ContentViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/photo/PhotoFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/photo/PhotoViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/UriToRequestBody.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_photo.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/values/strings.xml
Labels: fix 💥, 하은 🐰

#76 [fix] 위니 업로드 / 이미지뷰 scaleType 조정
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
Labels: fix 💥, 하은 🐰

#78 [feat] 마이페이지뷰 / 피드 삭제 시 누적위니, 누적회수 변경 반영
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MypageFragmentCallback.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/res/layout/fragment_recommend.xml
Labels: feat ✨, 상욱 🐨

#79 [fix] 위니 업로드 / 피드 업로드 중일 때는 버튼 클릭 불가능하도록 변경
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
Labels: fix 💥, 하은 🐰

#82 [chore] 사소해 사소해
  app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MypageFragmentCallback.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MypageHelpActivity.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
Labels: chore 🛠, 상욱 🐨

#81 [feat] 피드 / 무한스크롤 및 수정사항 적용
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetWineyFeedListDto.kt
  app/src/main/java/com/android/go/sopt/winey/domain/entity/WineyFeed.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedHighDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedLowDeleteDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteHighDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteLowDialogFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDialogViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
  app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/img_wineyfeed_default.xml
  app/src/main/res/layout/fragment_myfeed.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/layout/myfeed_empty.xml
Labels: feat ✨, 혜선 🐱

#83 [fix] 위니 업로드 / 금액 최대 길이 설정
  app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
  app/src/main/res/layout/fragment_amount.xml
Labels: fix 💥, 하은 🐰

#84 [fix] 프래그먼트 백스택 이슈 해결
  app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
Labels: fix 💥, 상욱 🐨

#87 [chore] qa 반영
  app/src/main/res/drawable/ic_main_recommend.xml
  app/src/main/res/values/strings.xml
Labels: chore 🛠, 상욱 🐨

#89 [ui] #88 디자인 QA 반영
  app/src/main/res/layout/item_recommend_header.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 상욱 🐨
