Repository team-winey/Winey-AOS, pull requests merged in 2024-02, with the labels that each got.

#235 [feat] 인앱 업데이트 기능 구현
  app/build.gradle.kts
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/ActivityLifecycleHandler.kt
  app/src/main/java/org/go/sopt/winey/WineyApplication.kt
  app/src/main/java/org/go/sopt/winey/presentation/splash/AppUpdateDialogFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/img_app_update_saver.xml
  app/src/main/res/layout/fragment_app_update_dialog.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/DefaultConfig.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: feat ✨, 하은 🐰

#237 [mod] 알림 권한 거부 시 뜨는 스낵바 디자인 변경
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/util/context/ContextExt.kt
  app/src/main/java/org/go/sopt/winey/util/fragment/FragmentExt.kt
  app/src/main/java/org/go/sopt/winey/util/view/snackbar/NotiPermissionSnackbar.kt
  app/src/main/java/org/go/sopt/winey/util/view/snackbar/SnackbarType.kt
  app/src/main/java/org/go/sopt/winey/util/view/snackbar/WineyFeedResultSnackbar.kt
  app/src/main/java/org/go/sopt/winey/util/view/snackbar/WineySnackbar.kt
  app/src/main/res/layout/layout_winey_snackbar.xml
  app/src/main/res/values/strings.xml
Labels: mod 〰, 하은 🐰

#241 [ui] 마이페이지 / V2 디자인 구현
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_mypage_airpods.xml
  app/src/main/res/drawable/ic_mypage_chicken.xml
  app/src/main/res/drawable/ic_mypage_coffee.xml
  app/src/main/res/drawable/ic_mypage_edit.xml
  app/src/main/res/drawable/ic_mypage_setting.xml
  app/src/main/res/drawable/ic_mypage_sneakers.xml
  app/src/main/res/drawable/ic_mypage_work.xml
  app/src/main/res/drawable/img_mypage_background_lv1.xml
  app/src/main/res/drawable/img_mypage_bubble_lv1.xml
  app/src/main/res/drawable/img_mypage_saver_lv1.xml
  app/src/main/res/drawable/shape_gray0_fill_16_rect.xml
  app/src/main/res/drawable/shape_gray0_fill_18_rect.xml
  app/src/main/res/drawable/shape_gray100_line_8_rect.xml
  app/src/main/res/drawable/shape_green100_rect.xml
  app/src/main/res/drawable/shape_purple400_line_8_rect.xml
  app/src/main/res/drawable/shape_red100_rect.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ui 🎨, 혜선 🐱

#240 [feat] 위니 업로드 / 과소비 플로우 추가
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedType.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/fragment/WineyDialogFragment.kt
  app/src/main/java/org/go/sopt/winey/util/intent/ArgsExt.kt
  app/src/main/java/org/go/sopt/winey/util/intent/BundleExt.kt
  app/src/main/java/org/go/sopt/winey/util/intent/IntentExt.kt
  app/src/main/java/org/go/sopt/winey/util/view/WineyPopupMenu.kt
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_photo.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#245 [feat] 마이페이지 / 유저 정보 조회 서버 연결 및 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/org/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/User.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/UserV2.kt
  app/src/main/java/org/go/sopt/winey/domain/repository/AuthRepository.kt
  app/src/main/java/org/go/sopt/winey/domain/repository/DataStoreRepository.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/ic_mypage_checked.xml
  app/src/main/res/drawable/ic_mypage_unchecked.xml
  app/src/main/res/drawable/img_mypage_background_lv2.xml
  app/src/main/res/drawable/img_mypage_background_lv3.xml
  app/src/main/res/drawable/img_mypage_background_lv4.xml
  app/src/main/res/drawable/img_mypage_bubble_lv2.xml
  app/src/main/res/drawable/img_mypage_bubble_lv3.xml
  app/src/main/res/drawable/img_mypage_bubble_lv4.xml
  app/src/main/res/drawable/img_mypage_saver_lv2.xml
  app/src/main/res/drawable/img_mypage_saver_lv3.xml
  app/src/main/res/drawable/img_mypage_saver_lv4.xml
  app/src/main/res/drawable/shape_gray200_line_8_rect.xml
  app/src/main/res/drawable/shape_gray50_fill_14_rect.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 혜선 🐱

#246 [ui] 목표여정 / 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel1Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel2Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel3Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel4Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_all_back.xml
  app/src/main/res/drawable/ic_help_back.xml
  app/src/main/res/drawable/ic_myfeed_back.xml
  app/src/main/res/drawable/ic_upload_back.xml
  app/src/main/res/drawable/img_goal_path_background_lv4.png
  app/src/main/res/drawable/img_goal_path_background_other.png
  app/src/main/res/drawable/img_goal_path_lv1_1.png
  app/src/main/res/drawable/img_goal_path_lv1_2.png
  app/src/main/res/drawable/img_goal_path_lv1_3.png
  app/src/main/res/drawable/img_goal_path_lv1_4.png
  app/src/main/res/drawable/img_goal_path_lv2_1.png
  app/src/main/res/drawable/img_goal_path_lv2_2.png
  app/src/main/res/drawable/img_goal_path_lv2_3.png
  app/src/main/res/drawable/img_goal_path_lv2_4.png
  app/src/main/res/drawable/img_goal_path_lv3_1.png
  app/src/main/res/drawable/img_goal_path_lv3_2.png
  app/src/main/res/drawable/img_goal_path_lv3_3.png
  app/src/main/res/drawable/img_goal_path_lv3_4.png
  app/src/main/res/drawable/img_goal_path_lv4.png
  app/src/main/res/drawable/shape_green_gray_fill_12_rect.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_goal_path.xml
  app/src/main/res/layout/activity_mypage_help.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_story.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_goal_path_level1.xml
  app/src/main/res/layout/fragment_goal_path_level2.xml
  app/src/main/res/layout/fragment_goal_path_level3.xml
  app/src/main/res/layout/fragment_goal_path_level4.xml
  app/src/main/res/layout/fragment_myfeed.xml
  app/src/main/res/raw/lottie_goal_path_step1.json
  app/src/main/res/raw/lottie_goal_path_step2.json
  app/src/main/res/raw/lottie_goal_path_step3.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 하은 🐰

#251 [mod] 위니, 상세, 마이 피드 / 피드 타입에 따라 아이템 디자인 변경
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetFeedDetailDto.kt
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetWineyFeedListDto.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/DetailFeed.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/WineyFeed.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/number/IntExt.kt
  app/src/main/res/drawable/shape_red100_fill_rect.xml
  app/src/main/res/drawable/shape_red500_line_6_rect.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_upload_dialog.xml
  app/src/main/res/layout/item_detail_feed.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/values/strings.xml
Labels: mod 〰, ui 🎨, 하은 🐰
