Repository team-winey/Winey-AOS, pull requests merged in 2024-03, with the labels that each got.

#257 [ui] 알림 뱃지 아이콘 색상 변경
  app/src/main/res/drawable/ic_wineyfeed_notification_new.xml
Labels: ui 🎨, 하은 🐰

#255 [feat] 위니피드 / 목표 달성 프로그레스바 구현
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/org/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/UserV2.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedGoalAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/UserLevel.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/login/LoginViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/progressbar_wineyfeed_goal.xml
  app/src/main/res/layout/fragment_amount.xml
  app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/layout/item_wineyfeed_goal.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/target_money.xml
  app/src/main/res/values/user_level.xml
Labels: feat ✨, 하은 🐰

#256 [feat] 목표여정 / 서버 연결
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponsePostWineyFeedDto.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedGoalAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel1Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel2Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel3Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/WineyDialogLabel.kt
  app/src/main/java/org/go/sopt/winey/presentation/nickname/NicknameActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/fragment/WineyDialogFragment.kt
  app/src/main/res/drawable/img_goal_path_background_lv4.png
  app/src/main/res/drawable/img_goal_path_lv4.png
  app/src/main/res/layout/activity_goal_path.xml
  app/src/main/res/layout/fragment_alert_dialog.xml
  app/src/main/res/layout/fragment_goal_path_level1.xml
  app/src/main/res/layout/fragment_goal_path_level2.xml
  app/src/main/res/layout/fragment_goal_path_level3.xml
  app/src/main/res/raw/lottie_goal_path_step2.json
  app/src/main/res/raw/lottie_goal_path_step3.json
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#259 [mod] 알림 목록 / 레벨업 가이드 화면 변경
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/adapter/WineyFeedAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/adapter/WineyFeedGoalAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/adapter/WineyFeedHeaderAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/adapter/WineyFeedLoadAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/notification/NotificationAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/WineyFeedType.kt
  app/src/main/java/org/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  buildSrc/src/main/java/DefaultConfig.kt
Labels: mod 〰, 하은 🐰

#261 [feat] 마이페이지 / 2주 절약, 낭비 기능 구현
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/org/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/UserV2.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/currency/MoneyCurrency.kt
  app/src/main/res/drawable/layer_mypage_progress_bar.xml
  app/src/main/res/drawable/shape_gray200_fill_8_rect.xml
  app/src/main/res/drawable/shape_gray400_fill_8_rect.xml
  app/src/main/res/drawable/shape_green500_fill_8_rect.xml
  app/src/main/res/drawable/shape_red500_fill_8_rect.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 혜선 🐱

#264 [ui] 온보딩 / 텍스트, 이미지 변경
  app/src/main/res/drawable/img_guide_wineyfeed.png
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 하은 🐰

#266 [ui] 마이페이지 / 이미지 리소스 교체 및 레이아웃 수정
  app/src/main/res/drawable/img_mypage_background_lv1.xml
  app/src/main/res/drawable/img_mypage_background_lv2.xml
  app/src/main/res/drawable/img_mypage_background_lv3.xml
  app/src/main/res/drawable/img_mypage_background_lv4.xml
  app/src/main/res/drawable/img_mypage_bubble_lv1.xml
  app/src/main/res/drawable/img_mypage_bubble_lv2.xml
  app/src/main/res/drawable/img_mypage_bubble_lv3.xml
  app/src/main/res/drawable/img_mypage_bubble_lv4.xml
  app/src/main/res/drawable/img_mypage_saver_lv1.xml
  app/src/main/res/drawable/img_mypage_saver_lv2.xml
  app/src/main/res/drawable/img_mypage_saver_lv3.xml
  app/src/main/res/drawable/img_mypage_saver_lv4.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: ui 🎨, 혜선 🐱

#267 [ui] 위니피드, 상세피드 / 리디자인 반영
  app/src/main/java/org/go/sopt/winey/presentation/main/MainViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_alert_dialog.xml
  app/src/main/res/layout/item_detail_feed.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 하은 🐰

#270 [mod] 마이피드, 목표여정 / 디테일 작업
  app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel1Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel2Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel3Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathLevel4Fragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/setting/SettingActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/notification/NotificationAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/nickname/NicknameActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/guide/GuideActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/splash/SplashActivity.kt
  app/src/main/java/org/go/sopt/winey/util/fragment/WineyDialogFragment.kt
  app/src/main/res/layout/activity_goal_path.xml
  app/src/main/res/layout/fragment_goal_path_level1.xml
  app/src/main/res/layout/fragment_goal_path_level2.xml
  app/src/main/res/layout/fragment_goal_path_level3.xml
  app/src/main/res/layout/fragment_goal_path_level4.xml
  app/src/main/res/layout/item_myfeed_post.xml
Labels: mod 〰, 하은 🐰
