Repository team-winey/Winey-AOS, pull requests merged in 2024-05, with the labels that each got.

#282 [mod] 목표 여정 / 황제 레벨 가이드 박스 변경
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
  app/src/main/res/layout/activity_goal_path.xml
  app/src/main/res/values/strings.xml
Labels: mod 〰, 하은 🐰, QA 🔎

#285 [ui] 피드 / 더보기 버튼 크기 변경
  app/release/output-metadata.json
  app/src/main/res/drawable/ic_feed_more.xml
  app/src/main/res/drawable/ic_wineyfeed_more.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_detail_comment.xml
  app/src/main/res/layout/item_detail_feed.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: ui 🎨, 하은 🐰, QA 🔎

#287 [merge] v1.1.0 내부 테스트 앱 QA 반영
  .github/ISSUE_TEMPLATE/bug_report.md
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedActivity.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/bg_story_lottie.png
  app/src/main/res/drawable/bg_story_lottie.xml
  app/src/main/res/drawable/ic_feed_more.xml
  app/src/main/res/drawable/ic_wineyfeed_more.xml
  app/src/main/res/layout/activity_goal_path.xml
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/layout/fragment_first_story.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_second_story.xml
  app/src/main/res/layout/fragment_third_story.xml
  app/src/main/res/layout/item_detail_comment.xml
  app/src/main/res/layout/item_detail_feed.xml
  app/src/main/res/layout/item_myfeed_post.xml
  app/src/main/res/layout/item_mypage.xml
  app/src/main/res/layout/item_wineyfeed_post.xml
  app/src/main/res/raw/lottie_consume_loading.json
  app/src/main/res/raw/lottie_save_loading.json
  app/src/main/res/values/consume_amount_range.xml
  app/src/main/res/values/consume_item_categories.xml
  app/src/main/res/values/save_item_categories.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: 하은 🐰, merge 🔀

#288 [ui] notification 아이콘 크기 변경
  app/release/output-metadata.json
  app/src/main/res/drawable/ic_noti_new.xml
  app/src/main/res/drawable/ic_noti_none.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  buildSrc/src/main/java/DefaultConfig.kt
Labels: ui 🎨, 하은 🐰

#290 [hotfix] 마이페이지 / 로딩 프로그레스바 추가
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: hotfix 🚨, 혜선 🐱

#292 [hotfix] junit test 디펜던시 버전 업그레이드
  buildSrc/src/main/java/Testing.kt
Labels: hotfix 🚨, 하은 🐰

#295 [merge] develop <- main
  app/release/output-metadata.json
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
  app/src/main/java/org/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/org/go/sopt/winey/domain/entity/UserV2.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_noti_new.xml
  app/src/main/res/drawable/ic_noti_none.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_winey_feed.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/DefaultConfig.kt
  buildSrc/src/main/java/Testing.kt
Labels: 하은 🐰, merge 🔀

#296 [fix] 설정 화면 / ConstraintLayout 제약 조건 오류 수정
  app/src/main/res/layout/activity_setting.xml
Labels: fix 💥, 하은 🐰

#297 [fix] 설정 화면 / ConstraintLayout 제약 조건 오류 수정
  app/src/main/res/layout/activity_setting.xml
Labels: fix 💥, 하은 🐰
