Repository team-winey/Winey-AOS, pull requests merged in 2024-04, with the labels that each got.

#276 [refactor] 마이페이지 / 디테일 작업, QA 반영
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetNotificationDto.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/adapter/WineyFeedGoalAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/SavePeriod.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/UserLevel.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/currency/MoneyCurrency.kt
  app/src/main/res/drawable/img_mypage_background_lv1.xml
  app/src/main/res/drawable/img_mypage_background_lv2.xml
  app/src/main/res/drawable/img_mypage_background_lv3.xml
  app/src/main/res/drawable/img_mypage_background_lv4.xml
  app/src/main/res/drawable/img_mypage_bubble_lv1.xml
  app/src/main/res/drawable/img_mypage_bubble_lv2.xml
  app/src/main/res/drawable/img_mypage_bubble_lv3.xml
  app/src/main/res/drawable/img_mypage_bubble_lv4.xml
  app/src/main/res/drawable/img_mypage_saver_lv1.xml
  app/src/main/res/drawable/img_mypage_saver_lv2.xml
  app/src/main/res/drawable/img_mypage_saver_lv3.xml
  app/src/main/res/drawable/img_mypage_saver_lv4.xml
  app/src/main/res/drawable/shape_gray0_fill_8_rect.xml
  app/src/main/res/layout/activity_guide.xml
  app/src/main/res/layout/fragment_goal_path_level4.xml
  app/src/main/res/layout/fragment_level_guide.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recommend_guide.xml
  app/src/main/res/layout/fragment_winey_feed_guide.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  gradlew
Labels: 혜선 🐱, refactor 🧹

#278 [fix] 마이페이지 / 2주 절약, 소비 애니메이션 깜빡임 현상 해결
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
Labels: fix 💥, 혜선 🐱

#271 [ui] 세계관 온보딩 / 세이버 크기 조정
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  app/src/main/java/org/go/sopt/winey/data/model/remote/response/ResponseGetNotificationDto.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/adapter/WineyFeedGoalAdapter.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/SavePeriod.kt
  app/src/main/java/org/go/sopt/winey/presentation/model/UserLevel.kt
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/java/org/go/sopt/winey/util/currency/MoneyCurrency.kt
  app/src/main/res/drawable/bg_story_lottie.png
  app/src/main/res/drawable/bg_story_lottie.xml
  app/src/main/res/drawable/img_mypage_background_lv1.xml
  app/src/main/res/drawable/img_mypage_background_lv2.xml
  app/src/main/res/drawable/img_mypage_background_lv3.xml
  app/src/main/res/drawable/img_mypage_background_lv4.xml
  app/src/main/res/drawable/img_mypage_bubble_lv1.xml
  app/src/main/res/drawable/img_mypage_bubble_lv2.xml
  app/src/main/res/drawable/img_mypage_bubble_lv3.xml
  app/src/main/res/drawable/img_mypage_bubble_lv4.xml
  app/src/main/res/drawable/img_mypage_saver_lv1.xml
  app/src/main/res/drawable/img_mypage_saver_lv2.xml
  app/src/main/res/drawable/img_mypage_saver_lv3.xml
  app/src/main/res/drawable/img_mypage_saver_lv4.xml
  app/src/main/res/drawable/shape_gray0_fill_8_rect.xml
  app/src/main/res/layout/activity_guide.xml
  app/src/main/res/layout/fragment_first_story.xml
  app/src/main/res/layout/fragment_goal_path_level4.xml
  app/src/main/res/layout/fragment_level_guide.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recommend_guide.xml
  app/src/main/res/layout/fragment_second_story.xml
  app/src/main/res/layout/fragment_third_story.xml
  app/src/main/res/layout/fragment_winey_feed_guide.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  gradlew
Labels: ui 🎨, 하은 🐰

#274 [feat] 피드 업로드 / 과소비 로딩 화면 추가
  app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/loading/LoadingActivity.kt
  app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedActivity.kt
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/raw/lottie_consume_loading.json
  app/src/main/res/raw/lottie_save_loading.json
  app/src/main/res/values/consume_amount_range.xml
  app/src/main/res/values/consume_item_categories.xml
  app/src/main/res/values/save_item_categories.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 하은 🐰

#280 [mod] 마이페이지 / 숫자, 문자 정렬
  app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
  app/src/main/res/layout/item_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 혜선 🐱, QA 🔎
